Vagrant.configure("2") do |config|
   config.vm.define "guest" do |guest|
      guest.vm.box = "hashicorp/bionic64"
      guest.vm.network  "public_network", ip: "192.168.33.16"
   config.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y ansible
      SHELL
   end
end























